### ISSUE TITLE
Brightness control

### ISSUE THREAD

**Issue by Keith94** [Soinou/Warmer#1]
f.lux has limited support for changing brightness of screen (via hotkeys only) but the dimming only lasts until sunrise. Can you possibly add persistent brightness control via slider to Warmer?

**Comment by Soinou** [comment]
I never tried to control the brightness of the computer using C# but I can probably try.

Though I'm not sure why you can't just control the brightness using Windows ?

In the power options you can change it if I recall correctly.

But well I need to add something to control that damn registry messing things up, so I guess I'll try to add brightness control while I'm at it.

**Comment by Keith94** [comment]
I figured that changing brightness via app would be more convenient than via monitor settings and such. Since f.lux has a similar feature it would be suitable here as well.

Off topic, my displays go to sleep after one hour, after waking them up I noticed that Warmer had stopped working; I had to toggle it off and on again to fix the temperature.

What do you mean about the registry also?

**Comment by Soinou** [comment]
Yeah I noticed that sometimes when the screen goes off and on (Or when a new screen is connected or stuff like that), it goes away to never go back until you tell it to go back. I never really checked this but I'll try to check it as well.

And by the registry I mean that there's a key that needs to be set in the registry to be able to set the temperature to <3500K. I tried to add this key in the setup but it seems like it doesn't work so I'll have to add something inside the app to add this damn key.

**Comment by Keith94** [comment]
Interesting, the lowest it will go seems to be only 3300K.

Well if you need any beta testing or feedback just let me know. I think it could be a good replacement for f.lux, so I look forward to any improvements. :)

**Comment by Soinou** [comment]
Alright after a bit of research and coding, here's what I found:

It seems changing the screen brightness is possible using the same thing I already use to change the screen temperature. The only problem is that the code was mostly taken from the Redshift project, and I have absolutely no idea how it works and I don't want to break it.

Also, from what I could understand, it would change the screen brightness by modifying the screen gamma, which is not actually changing the monitor brightness, and therefore is probably not as good as manually updating the physical monitor settings. I'm not entirely sure though.

In the end, I'm not sure I will be able to add brightness support in the near future, but I'll try sometime to check if this is possible.

I also checked a bit why the color update seems to "crash" from time to time and I have no idea why that is for now, I'll continue to check a bit.

But well, at least I was able to add something to update the registry key from the application, should probably work, I'll try to push it soon.

**Comment by Keith94** [comment]
I see, thanks for taking a look. I got the new version now, just haven't restarted yet.

It would be nice to get a fix for the "crash" at some point as well.

Regarding brightness/gamma, I did find [Monitor Class (WinAPI)](https://github.com/jNizM/Class_Monitor), as well as [Redshift GUI](https://github.com/maoserr/redshiftgui/downloads) which has individual brightness and temperature sliders.

The program itself has some annoying bugs, and hasn't been updated in a while. I guess there is no way to 'port' any code over to your project?

![redshiftgui_2016-10-25_16-25-59](https://cloud.githubusercontent.com/assets/5490615/19707940/f7f17698-9acf-11e6-9a7c-c3f432117514.png)

**Comment by Keith94** [comment]
Also, it seems odd that the program installs itself to %APPDATA% by default; usually binaries don't get copied to that folder. Would it be better to change to Program Files (x86) by default instead?

**Comment by Soinou** [comment]
Didn't know about Redshift GUI, I might look into it to check how they change the brightness.

Also the %APPDATA% directory is kinda the "new" Program Files now, some new applications are installed there.

I think it's better to put it there because this directory doesn't require administrator rights to write, and I can therefore write config files without having to start the application as administrator.

**Comment by Keith94** [comment]
Okay, thanks!
